name: Python Version server test run

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt

      - name: Run tests
        run: |
          cd python
          pytest

      - name: Upload decision tree visualization to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: decision-tree-visualization
          path: python/output/decision_tree.png
